services:
  bind9:
    image: internetsystemsconsortium/bind9:9.20
    container_name: bind9
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bind:/etc/bind
      - /var/cache/bind \
      - /var/lib/bind \
      - /var/log \
    restart: unless-stopped
